[package]
name = "Override-934Z"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "z"
lto = "fat"

# These fields configure default behavior for uploads with `cargo v5`.
[package.metadata.v5]
upload-strategy = "differential"
slot = 1
icon = "cool-x"
compress = true

[dependencies.vexide]
git = "https://github.com/vexide/vexide"
features = ["full"]

[target.'cfg(target_os = "vexos")'.dependencies]
vex-sdk-jumptable = { git = "https://github.com/vexide/vex-sdk" }

[target.'cfg(not(target_os = "vexos"))'.dependencies]
vex-sdk-desktop = { git = "https://github.com/vexide/roboscope" }

[dependencies]
bloblib = { git = "https://github.com/Blueblob860/bloblib-vex-v5.git" }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

[workspace]
members = ["simulator"]
